Fix issue #1: add --output

diff --git a/test/nancy-test b/test/nancy-test
--- a/test/nancy-test
+++ b/test/nancy-test
@@ -3,6 +3,11 @@
 
 set -e
 
+# Read and process arguments
+if [ "$1" = "--output" ]; then
+    USE_OUTPUT_FILE=yes
+    shift
+fi
 SRC=$1
 TEMPLATE=$2
 PAGES=$3
@@ -11,11 +16,20 @@ STDIN_TEMPLATE=$5
 if [ -z "$5" ]; then
     STDIN_TEMPLATE="&1"
 fi
+
+# Run test
 rm -rf dest
 NANCY_CMD=(../nancy --verbose --root "$SRC" "$TEMPLATE")
 #NANCY_CMD=(perl -wMDevel::SimpleTrace ../nancy --verbose --root "$SRC" "$TEMPLATE")
 for page in $PAGES; do
+    STDOUT_ARGUMENT=""
+    NANCY_EXTRA_ARGS=()
+    if [ "$USE_OUTPUT_FILE" = "yes" ]; then
+        NANCY_EXTRA_ARGS=("--output" "dest/$page")
+    else
+        STDOUT_ARGUMENT='>dest/$page'
+    fi
     mkdir -p "`dirname \"dest/$page\"`"
-    eval '"${NANCY_CMD[@]}"' '$page' "<$STDIN_TEMPLATE" > dest/$page || ( printf "Test in \`$SRC' failed to run\n" && exit 1 )
+    eval '"${NANCY_CMD[@]}"' '"${NANCY_EXTRA_ARGS[@]}"' '$page' "<$STDIN_TEMPLATE" "$STDOUT_ARGUMENT" || ( printf "Test in \`$SRC' failed to run\n" && exit 1 )
 done
 diff -Nur $EXPECTED dest || ( printf "Test in \`$SRC' produced incorrect output\n" && exit 1 )
